name: Unity Test Runner  # Replace with a descriptive name

on:  # Define event triggers (e.g., push, pull_request)
  push:
    branches: [ main ]  # Example trigger on pushes to the "main" branch

jobs:
  test:  # Replace with a descriptive name for the job
    runs-on: ubuntu-latest  # Specify runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      # Add your additional steps here if needed (e.g., install dependencies)

      - uses: game-ci/unity-test-runner@v4  # Run Unity tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}
