name: Build test1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Unity Project
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Pre-install Unity Hub on a dedicated runner (not shown in this script)

    - name: Set Unity Hub path (assuming pre-installation)
      run: |
        export PATH="$HOME/.local/bin:$PATH"  # Replace with your pre-installed Unity Hub path
        echo "UNITY_HUB_PATH=$HOME/.local/bin/unityhub"  # Replace with your pre-installed Unity Hub path

    - name: Install Dependencies
      run: |
        # Add commands here to install any dependencies required for your Unity project
        # For example, you might need to install Node.js, npm packages, etc.

    - name: Build Unity Project (with shebang line and `sh` interpreter)
      run: |
        #!/bin/bash  # Added shebang line

        sh $UNITY_HUB_PATH --quit -batchmode -projectPath "$GITHUB_WORKSPACE/test1" -buildTarget StandaloneLinux64 -executeMethod UnityEditor.BuildPlayerWindow+BuildMethod.BuildPlayer -logFile "$GITHUB_WORKSPACE/build.log"

    # Add other steps for testing, deploying, or other tasks as needed
