name: Build test1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Unity Project
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Unity Hub installer
        run: |
          curl -o UnityHub.dmg https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg

      - name: Install Unity Hub
        run: |
          mkdir -p $GITHUB_WORKSPACE/Applications
          hdiutil attach UnityHub.dmg
          cp -R /Volumes/Unity\ Hub\ 3.7.0/Unity\ Hub.app $GITHUB_WORKSPACE/Applications/
          hdiutil detach /Volumes/Unity\ Hub\ 3.7.0

      - name: Install Dependencies
        run: |
          # Add commands here to install any dependencies required for your Unity project
          # For example, you might need to install Node.js, npm packages, etc.

      - name: Build Unity Project
        run: |
          # Execute the Unity command line to build the project
          # Adjust the path to Unity executable and project directory
          $GITHUB_WORKSPACE/Applications/Unity\ Hub.app/Contents/MacOS/Unity -quit -batchmode -projectPath $GITHUB_WORKSPACE/test1 -buildTarget StandaloneLinux64 -executeMethod UnityEditor.BuildPlayerWindow+BuildMethod.BuildPlayer -logFile $GITHUB_WORKSPACE/build.log

      # Add other steps for testing, deploying, or other tasks as needed
