name: Build and Test Unity Project

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: macos-latest  # Replace with the desired runner OS (Windows or Linux)
    steps:
    - uses: actions/checkout@v3

    # Pre-install Unity Hub on a dedicated runner with proper access permissions (not shown in this script)

    - name: Set environment variables
      run: |
        # Replace with actual path to Unity Hub and project directory
        export UNITY_HUB_PATH=/path/to/unityhub
        export PROJECT_DIR="$GITHUB_WORKSPACE/your_project_name"
        echo "UNITY_HUB_PATH=$UNITY_HUB_PATH"
        echo "PROJECT_DIR=$PROJECT_DIR"

    - name: Install Dependencies (optional)
      run: |
        # Add commands here to install any dependencies required for your project
        # For example, npm install

    - name: Build Unity Project
      run: |
        $UNITY_HUB_PATH --quit -batchmode -projectPath "$PROJECT_DIR" -buildTarget StandaloneLinux64 -executeMethod UnityEditor.BuildPlayerWindow+BuildMethod.BuildPlayer -logFile "$PROJECT_DIR/build.log"

    # Add other steps for testing, deploying, or other tasks as needed

