name: Build test1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Unity
        run: |
          curl -o UnityHubSetup.AppImage https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
          chmod +x UnityHubSetup.AppImage
          ./UnityHubSetup.AppImage --install-location=$HOME/UnityHub --unattended

      - name: Install Unity Editor
        run: $HOME/UnityHub/UnityHub.AppImage unityhub://install/2022.3.11f1

      - name: Install Dependencies
        run: |
          # Install any dependencies required for your Unity project
          # For example, you might need to install Node.js, npm packages, etc.

      - name: Build Unity Project
        run: |
          # Execute the Unity command line to build the project
          # Replace 'ProjectName' with the actual name of your Unity project
          # Modify the build options as needed (e.g., platform, build path)
          unity -quit -batchmode -projectPath $GITHUB_WORKSPACE/test1 -buildTarget StandaloneLinux64 -executeMethod UnityEditor.BuildPlayerWindow+BuildMethod.BuildPlayer -logFile build.log
